Rebuild image using Elyra
aicoe-aiops/ocp-ci-analysis pull request #127
Opened 2021-02-11 17:42 UTC by pacospace

Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

## Related Issues and Dependencies

Related-To: https://github.com/aicoe-aiops/ocp-ci-analysis/issues/109

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

Change base image to have s2i lab Elyra as base.

@martinpovolny No other changes seems to be required, as the image will pick latest tag and ArgoCD already watches the imagestream related: https://github.com/operate-first/apps/blob/master/odh/base/jupyterhub/notebook-images/ocp-ci-analysis.yaml

2021-02-11 18:49 UTC, MichaelClifford approved these changes

2021-02-11 19:20 UTC, MichaelClifford commented
@pacospace any idea why the build-check is failing here?

2021-02-11 19:24 UTC, pacospace commented
> @pacospace any idea why the build-check is failing here?

actually yes, give me one moment!

2021-02-11 19:25 UTC, pacospace commented
/retest

2021-02-12 08:44 UTC, pacospace commented
> > @pacospace any idea why the build-check is failing here?
> 
> actually mmm, give me one moment!

The build failed, even though it says completed and it is green:

```
---> Installing application source ...
mv: inter-device move failed: '\''/tmp/src/.git'\'' to '\''/opt/app-root/src/.git'\''; unable to remove target: Directory not empty
mv: inter-device move failed: '\''/tmp/src/.github'\'' to '\''/opt/app-root/src/.github'\''; unable to remove target: Directory not empty
subprocess exited with status 1
subprocess exited with status 1
error building at STEP "RUN /opt/app-root/builder/assemble": exit status 1'
+ exit_code=1
+ set -e
+ [[ 1 -ne 0 ]]
+ state=failure
+ desc='The image build test failed!'
+ cat
```

2021-02-12 08:48 UTC, harshad16 commented
/hold

2021-03-18 14:08 UTC, harshad16 requested changes
Please use the s2i-elyra-custom-notebook image as  the base image.
This is a sibling image of s2i-custom-notebook, with elyra support bits added.

2021-03-18 14:08 UTC, harshad16 commented on .aicoe-ci.yaml
> +  base-image: quay.io/thoth-station/s2i-lab-elyra:v0.0.5
```suggestion
  base-image: quay.io/thoth-station/s2i-elyra-custom-notebook:latest 
```

2021-03-18 14:35 UTC, pacospace commented
/unhold

2021-03-22 12:29 UTC, tumido commented
please read https://chat.google.com/room/AAAAQcVnQvs/kDNfLz86AMs before unholding

2021-03-25 12:58 UTC, pacospace commented
@harshad16 any updates?

2021-03-25 13:02 UTC, harshad16 commented
/retest

2021-03-25 20:33 UTC, sesheta commented
@pacospace: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-03-26 07:33 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aicoe-aiops/ocp-ci-analysis/pull/127#pullrequestreview-588879535" title="Approved">MichaelClifford</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aicoe-aiops%2Focp-ci-analysis).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/aicoe-aiops/ocp-ci-analysis/blob/master/OWNERS)~~ [MichaelClifford]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-04-07 15:16 UTC, pacospace commented
/retest

2021-04-22 13:32 UTC, harshad16 commented
The base image has some issue which has caused the hold-up.
The custom base notebook is having trouble as there seem to be pre-existing patches included in the image.
we are investigating and trying to resolve this. 
sorry for the delay and inconvenience.

2021-04-26 13:11 UTC, harshad16 commented
/retest

2021-04-26 13:43 UTC, harshad16 commented
/retest

2021-04-26 19:41 UTC, harshad16 commented
The base image is fixed.
unholdin the pr.
/unhold.

2021-04-26 19:41 UTC, harshad16 commented
/unhold

2021-04-26 20:13 UTC, harshad16 commented
https://github.com/aicoe-aiops/ocp-ci-analysis/issues/246

2021-04-27 15:09 UTC, harshad16 commented
/test pre-commit

2021-04-27 15:11 UTC, merged