[WIP] Catch up with latest project-template changes.
aicoe-aiops/ocp-ci-analysis pull request #141
Opened 2021-03-03 10:23 UTC by martinpovolny

## Related Issues and Dependencies

Reflects
https://github.com/aicoe-aiops/project-template/pull/30

## This introduces a breaking change

- [ ] Yes
- [ ] No

It specifies python 3.8, we have 3.6 in the Pipfile, need to fix this.

## This Pull Request implements

Update to the latest changes in the project-template

## Description

As explained in the related PR as "some minor updates to the CI configuration" probably the main change is the new Python version.

2021-03-03 11:19 UTC, tumido reviewed
1 comment, other than that

/lgtm

2021-03-03 11:19 UTC, tumido commented on .aicoe-ci.yaml
> +# b
Is this intentional or a blip?

2021-03-03 16:00 UTC, tumido reviewed
/lgtm

seems like a conflict somewhere

2021-03-03 16:01 UTC, martinpovolny commented
Yes, the same was done here: https://github.com/aicoe-aiops/ocp-ci-analysis/pull/140

Except for updating the Pipfiles to 3.8.

2021-03-03 16:03 UTC, martinpovolny commented
I did not notice that @goern created the PR while also pinging in the channel about updating projects. My bad.

But we should update the Pipfiles to 3.8 anyway. Shouldn't we?

2021-03-03 16:07 UTC, tumido commented
@martinpovolny I don't think it's necessary for you to upgrade to Python 3.8. On the other hand if there's anything actually holding you back I see no reason why shouldn't you upgrade. :) So I'd say it's up to you.

2021-03-04 09:27 UTC, martinpovolny commented
@tumido : are you saying that it's ok to have python 3.8 in thoth's config and use 3.6 in the Pipfile?

2021-03-04 13:45 UTC, tumido commented
@martinpovolny I think you should remain consistent. Precommit for python 3.6 behaves differently to precommit 3.8 for example - because the language is different a tiny bit. So if you require your app to use Python 3.6 in Pipfile, you should stick with 3.6 in thoth's config. But if there's nothing blocking you to upgrade your Pipfile to 3.8, I'd say you fully upgrade to 3.8.

2021-03-05 13:22 UTC, martinpovolny commented
/retest

2021-03-05 14:47 UTC, harshad16 requested changes
Good to see, project migrating to python 3.8
This is to be updated https://github.com/aicoe-aiops/ocp-ci-analysis/blob/42412bbe6dc98592edecd0c2568bb75eaa127b6e/.aicoe-ci.yaml#L9 with quay.io/thoth-station/s2i-custom-py38-notebook:latest

2021-03-05 15:15 UTC, martinpovolny commented
@harshad16 : thanks for the explanation. I hoped to get to some meaningful error myself but when clicking on the "build-check" link above I get only "Error loading PipelineRun" and "PipelineRun not found"

And this is shortly after I requested the `/rebuild` so the data should not have been removed yet.

2021-03-05 15:51 UTC, harshad16 commented
I hoped to get to some meaningful error myself but when clicking on the "build-check" link above I get only "Error loading PipelineRun" and "PipelineRun not found"

This happens sometimes, for me readload works 
we would work on upgrading the dashboard as well
actually we had migrated the build to operate-first last week, but due to the upgrade of operate-first , we switched the app to psi
once the operate-first is available , we would have more flexibility to uprgade and provide the services in more efficient manner.

2021-03-20 20:33 UTC, sesheta commented
@martinpovolny: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-03-22 12:28 UTC, tumido commented
/hold please read https://chat.google.com/room/AAAAQcVnQvs/kDNfLz86AMs before unholding

2021-03-25 17:05 UTC, closed without merging