Update template for automation
aicoe-aiops/ocp-ci-analysis pull request #209
Opened 2021-04-02 15:12 UTC by MichaelClifford

## Related Issues and Dependencies
related to #207 

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

This PR adds a few more standards to the `metric_template` notebook that using it as part of an automation pipeline easier.

* added a `METRIC_NAME` variable, so that it need only be defined once at the top of the file.
* added an `s3_input_data_path` variable to control where in ceph or notebooks pull data from.
* added an `AUTOMATION` environment variable so that we can control notebook behavior between DS and automation use cases. 
* updated "Import data" step to pull from a ceph bucket when in "automation" .
* added timestamps to output filenames.
* changed the default output filename format to ensure each metric exists in its own directory.
* updated save_to_disk to check for, and make directory if missing, before saving.

2021-04-02 15:12 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **michaelclifford** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @michaelclifford` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aicoe-aiops%2Focp-ci-analysis).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/aicoe-aiops/ocp-ci-analysis/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["michaelclifford"]} -->

2021-04-05 13:11 UTC, Shreyanand requested changes
LGTM, nice changes! Just a minor suggestion: we could add code for the "save-to-disk" function to be called only when this notebook is run out of automation. That way we set the right default for it and we also have an example of how to use the "automation" flag in the notebooks.

2021-04-05 14:27 UTC, MichaelClifford commented
@Shreyanand please take a look at the new changes

2021-04-05 14:37 UTC, aakankshaduggal reviewed
/lgtm

2021-04-05 14:41 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

Approval requirements bypassed by manually added approval.

This pull-request has been approved by:

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aicoe-aiops%2Focp-ci-analysis).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/aicoe-aiops/ocp-ci-analysis/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["michaelclifford"]} -->

2021-04-05 14:42 UTC, merged